springdoc:
  swagger-ui:
    oauth:
      client-id: spring
      client-secret: qw7OaNyi5MQuNDfSsSgKxQmNOSMdHm51

server:
  port: 8081

realm: spring-test
server-url: http://localhost:8080
client-id: admin-cli
grant-type: password
name: admin
password: admin
